# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'VonageChatSDKExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VonageChatSDKExampleApp
   pod 'VonageClientSDKChat', '1.2.1'

  target 'VonageChatSDKExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VonageChatSDKExampleAppUITests' do
    # Pods for testing
  end

end
