# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
target 'VonageSDKClientVOIPExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VonageSDKClientVOIPExample
  pod 'VonageClientSDKVoice', '2.2.0-snapshot.152.0'

end
